name: webui

on:
  workflow_call:

jobs:
  build:
    continue-on-error: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use LTS version only
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v5
    - name: Glances will be build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./glances/outputs/static/package-lock.json
    - name: Build Glances WebUI
      working-directory: ./glances/outputs/static
      run: |
        npm ci
        npm run build
    - name: Commit and push WebUI
      env:
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "glances@nicolargo.com"
        git add glances/outputs/static
        /bin/bash -c "git commit -m '${{ env.CI_COMMIT_MESSAGE }}' || true"
        git push
